"""initial migration

Revision ID: 15d84b2f955c
Revises: 93480fcc2afc
Create Date: 2023-11-08 10:25:13.342601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '15d84b2f955c'
down_revision: Union[str, None] = '93480fcc2afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consignor_copy', 'cin')
    op.drop_column('consignor_copy', 'gst_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignor_copy', sa.Column('gst_no', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('consignor_copy', sa.Column('cin', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
