"""initial migration

Revision ID: 93480fcc2afc
Revises: c4ac70b4654f
Create Date: 2023-11-08 09:31:40.671222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93480fcc2afc'
down_revision: Union[str, None] = 'c4ac70b4654f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consignor_copy', sa.Column('gst_no', sa.String(length=50), nullable=True))
    op.add_column('consignor_copy', sa.Column('cin', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('consignor_copy', 'cin')
    op.drop_column('consignor_copy', 'gst_no')
    # ### end Alembic commands ###
