"""initial migration

Revision ID: e5c1e69b5d8b
Revises: f2809db05b22
Create Date: 2023-11-08 14:05:06.833559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5c1e69b5d8b'
down_revision: Union[str, None] = 'f2809db05b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', mysql.TINYINT(), nullable=True, comment=' 1->Admin; 2->user'),
    sa.Column('f_name', sa.String(length=50), nullable=True),
    sa.Column('l_name', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=True),
    sa.Column('email_id', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=5000), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True, comment="ForeignKey('user.id')"),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='0->inactive,1->active,-1->deleted'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
